FROM python:3.10-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    gcc \
    python3-dev \
    libgl1-mesa-glx \
    libglib2.0-0

COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY models /app/models
COPY . .

CMD ["celery", "-A", "main.celery_app", "worker", "--loglevel=info"]
